### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by fiveisprime**
Updated the readme to add a little more about the project and to
include a section on getting help/discussing the exercises. Also
added myself as the lead maintainer to be responsible for said help
as well as maintenance going forward.

Related to https://github.com/hapijs/contrib/issues/33

TODO: add a section in the readme about the hapijs code of conduct once
the contrib pull request is merged.

### CODE REVIEW

**Comment by hueniverse** [comment]
Thanks @fiveisprime. I don't have npm rights so you will have to ask one of those people to add you there.

**Comment by lloydbenson** [comment]
I can help with this, I just need to know your npm account name.  Feel free to email me with the details if you don't want to share it here.

**Comment by lloydbenson** [comment]
I did make a guess and added fiveisprime already so that might be sufficient (or sufficient enough for you to change it to another one of your accounts).  Let me know if you need anything else and thanks for the help!

**Comment by fiveisprime** [comment]
@lloydbenson That's perfect, thanks! :)

**Pull request merged**
