### PR TITLE
Clarify query and fix the solution so it actually matches the problem

### PR DESCRIPTION
**Pull request by lloydbenson**
The solution in views it appears doesn't actually meet the requirements of the problem which was to have a file named index.html not template.html as the solution has.  Users would still pass, but the real solution at the end would be incorrect.  Also clarified an instruction another PR was trying to address.

### CODE REVIEW

**Comment by devinrhode2** [comment]
Looks fine. I started re-writing portions of the exercise to make the entire thing more clear, but I have no clear place to commit those changes. Can you please merge this? I can then do a clean commit on master.

**Comment by lloydbenson** [comment]
@devinrhode2 do you have an ETA on the rewrite?  Reason I ask is I am getting ready for a publish here with the updates and if you were almost done I'd wait a bit to include them.  If I don't hear back shortly, I'll assume you got busy.

**Comment by devinrhode2** [comment]
yeah don't wait



-Devin <http://zerply.com/DevinRhode2>
<http://zerply.com/devinrhode2>

**Comment by lloydbenson** [comment]
I didn't.  New version is published.

**Pull request merged**
