### PR TITLE
Closes #125

### LINKED ISSUE #125: update "views" exercise text to promote real templating
Currently the "views" exercise does not say that test is whether the URL query argument "name" is passed into the template that is saved to the templates dir; there is nothing in the assignment or hints to suggest that the template should have a `{{...}}` construction in it.

The assignment currently shows the "desired output HTML", so if someone is copy-pasting the hints in order to build out their program (which they will be) there is nothing in the hints to suggest a `{{query.name}}` is needed in order to pass the test. For people new to hapi/templating, the assignment is likely to end up as "copy the HTML, save as file, return that file on requests for `/`, done. My program generates the correct output without any templating magic, I'm not sure what I was supposed to learn about templating?".

(Of course, those of us already familiar with mustache/jinja/nunjucks/etc know what is required, but there will be a substantial group for whom this is their first exposure to templating, and the exercise forgets to explicitly say that a {{query.name}} or the like is needed in the HTML that goes in the template's index.html)

### PR DESCRIPTION
**Pull request by lloydbenson**

### CODE REVIEW

**Comment by nvcexploder** [comment]
@Pomax that's a good idea - would you like to implement?

**Comment by Pomax** [comment]
I'm not the right person for that, I think. I'll be happy to note my findings and recommend what I think makes sense, but ultimately I'm also just following the makemehapi assignments so it's more valuable to have people who know what they want to teach implement the actual changes.

**Comment by nvcexploder** [comment]
Sounds good. If you are interested in contributing to the ecosystem, please feel free to join our mentor program. :)

**Comment by lloydbenson** [comment]
Closing this PR as it didn't address enough of @Pomax concerns.

**Pull request closed without merging**
