### PR TITLE
Update solutions to use consistent Path.join

### PR DESCRIPTION
**Pull request by lifeiscontent**
Just for consistency sake

### CODE REVIEW

**Comment by lloydbenson** [comment]
Thanks!

**Comment by lifeiscontent** [comment]
@lloydbenson thats what I like to see. Thanks for the fast response. I'll be making more contributions in the future if I see anything else! :+1:

**Comment by lloydbenson** [comment]
This repo could use some love so it would be greatly appreciated!

**Comment by lifeiscontent** [comment]
@lloydbenson I'm having trouble following the material. Would you be interested in helping me learn and in return I'll rewrite the app from what you or someone in the community can teach?

**Pull request merged**
