### PR TITLE
Fixed solution to cookies problem

### PR DESCRIPTION
**Pull request by tdd**
Hi there!

The cookies problem says nothing about a path requirement (and the solution's path is a wildcard anyway), but this prevents valid solutions from matching output, so I removed it.

Also, the solution's `/check-cookie` handler forgot its state config, so it systematically failed to see the cookie and always returned an error, when it should have seen the cookie and said OK.

So here goes!

### CODE REVIEW

**Comment by nvcexploder** [comment]
Howdy @tdd! I like having at least a small path in there, take a look at https://github.com/hapijs/makemehapi/pull/142/files and let me know what you think of that one.

**Comment by tdd** [comment]
Hey!

I see your point, but again, the problem only says Hapi "provides a way to manage cookies for specific URL paths", when the solution mandates both paths to share the cookie, so it's either no path or `/` path. Both are equally valid.

Perhaps if you were to reword the problem (or its hints) so people understand you *want* a path in the session settings, then I'd see no trouble with using `/` in the solution?

**Comment by nvcexploder** [comment]
I think that sounds like the best option - I'll put that in there tomorrow.
I'm in the midst of changing a bunch of the copy in the problems anyway. :)

Thanks for your help! :D

**Comment by fiveisprime** [comment]
@tdd #142 is merged and appears to solve the same issue. Can you confirm that
is the case?

**Pull request closed without merging**
